### ISSUE TITLE
Cannot resolve type: "MCL_BLS12_381.fp" 

### ISSUE THREAD

**Issue by genievot** [aeternity/aeproject#412]
**Describe the bug**
When using code from this repo https://github.com/genievot/zk-ae-private-transactions/ and do `aeproject test`.

**To Reproduce**
1. Please clone the `main` branch from this repo https://github.com/genievot/zk-ae-private-transactions/
2. Install Dependencies
3. Run aeprject nodes 
4. Then run `aeproject test`
5. The error I got:
```
TypeResolveError: Cannot resolve type: "MCL_BLS12_381.fp"
      at TypeResolver.resolveType (node_modules/@aeternity/aepp-calldata/src/TypeResolver.js:231:15)
      at TypeResolver.resolveType (node_modules/@aeternity/aepp-calldata/src/TypeResolver.js:126:25)
      at /home/ubuntu/aeternity-projects/bounty/zkp-aes/node_modules/@aeternity/aepp-calldata/src/TypeResolver.js:251:56
      at Array.map (<anonymous>)
      at TypeResolver.resolveRecord (node_modules/@aeternity/aepp-calldata/src/TypeResolver.js:251:42)
      at TypeResolver.resolveType (node_modules/@aeternity/aepp-calldata/src/TypeResolver.js:212:25)
      at TypeResolver.resolveType (node_modules/@aeternity/aepp-calldata/src/TypeResolver.js:126:25)
      at TypeResolver.resolveType (node_modules/@aeternity/aepp-calldata/src/TypeResolver.js:126:25)
      at /home/ubuntu/aeternity-projects/bounty/zkp-aes/node_modules/@aeternity/aepp-calldata/src/TypeResolver.js:251:56
      at Array.map (<anonymous>)
      at TypeResolver.resolveRecord (node_modules/@aeternity/aepp-calldata/src/TypeResolver.js:251:42)
      at TypeResolver.resolveType (node_modules/@aeternity/aepp-calldata/src/TypeResolver.js:212:25)
      at TypeResolver.resolveType (node_modules/@aeternity/aepp-calldata/src/TypeResolver.js:126:25)
      at TypeResolver.getReturnType (node_modules/@aeternity/aepp-calldata/src/TypeResolver.js:79:21)
      at Encoder.decode (node_modules/@aeternity/aepp-calldata/src/Encoder.js:99:41)
      at Object.c.call (node_modules/@aeternity/aepp-sdk/dist/aepp-sdk.js:1:97822)
      at processTicksAndRejections (internal/process/task_queues.js:95:5)
      at async Context.<anonymous> (test/zkp_verify_test.js:34:17)
```

**Expected behavior**
I expected to not have predefined data type errors.

**Screenshots**
![image](https://user-images.githubusercontent.com/40867747/161108261-52bb319a-e10f-4d2b-9c77-4b799bc1ba35.png)

**Please tell us about your environment:**

  - Node Version: v14.18.3
  - Protocol Version: Latest
  - Aeproject:  v4.0.0-beta.6
  - Compiler version: Docker node from latest beta
  - VM Version: fate | fate2
  - SDK Version: From aeproject beta 
  - Python version: v3.7.5

**Comment by thepiwo** [comment]
this only seems to be an  issue with https://github.com/aeternity/aepp-calldata-js can you open a full issue there?

**Comment by marc0olo** [comment]
yes, we already have the issue there:
- https://github.com/aeternity/aepp-calldata-js/issues/126
