### ISSUE TITLE
`awaitKeyBlocks` throwing error using a high keyblock delta

### ISSUE THREAD

**Issue by marc0olo** [aeternity/aeproject#470]
## Expected behavior
Following code emits 600 keyblocks without an error.

```js
await utils.awaitKeyBlocks(aeSdk, 600);
```

## Actual behavior
Following error occurs:

```sh
Error: HTTP status code 500
    at ClientRequest.<anonymous> (/home/marc0olo/git/aeternity/marc0olo/aens-nfts/development/smart-contracts/node_modules/@aeternity/aeproject/src/utils/utils.js:28:21)
    at Object.onceWrapper (node:events:642:26)
    at ClientRequest.emit (node:events:527:28)
    at HTTPParser.parserOnIncomingClient (node:_http_client:631:27)
    at HTTPParser.parserOnHeadersComplete (node:_http_common:128:17)
    at Socket.socketOnData (node:_http_client:494:22)
    at Socket.emit (node:events:527:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
```

## Version information
- aeproject: `v4.6.1`
- node: `v6.8.1-bundle`

**Comment by marc0olo** [comment]
initially I tried with a `BigInt` of `179519n`. but it is already reproducable with a regular number `600` as outlined above.

my current guess is that the problems occurs with a delta ~500 keyblocks

**Comment by marc0olo** [comment]
passing `BigInt` will anyway break the function on execution of this line `await aeSdk.awaitHeight(height + n);`

error:
```sh
TypeError: Cannot mix BigInt and other types, use explicit conversions
      at Object.awaitKeyBlocks (node_modules/@aeternity/aeproject/src/lib/utils.js:70:34)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at async Context.<anonymous> (test/aensWrappingTest.js:621:9)
```

**Comment by thepiwo** [comment]
you won't be needing bigint for the amount of blocks that are usually interesting, if we get to those numbers we would experience different issues

**Comment by marc0olo** [comment]
true, but is is just convenience as bigint is needed sometimes to check results in tests

**Comment by thepiwo** [comment]
https://github.com/aeternity/aeternity/pull/4164
https://github.com/aeternity/aeplugin_dev_mode/pull/25

PRs open to resolve this upstream

**Comment by marc0olo** [comment]
can be closed I guess @thepiwo. just re-open if not :)
